var houses = { 'houses:1': 'House Algood',
  'houses:10': 'House Baelish of Harrenhal',
  'houses:100': 'House Deddings',
  'houses:101': 'House Doggett',
  'houses:102': 'House Dondarrion of Blackhaven',
  'houses:103': 'House Donniger',
  'houses:104': 'House Drinkwater',
  'houses:105': 'House Drox',
  'houses:106': 'House Drumm of Old Wyk',
  'houses:107': 'House Dryland',
  'houses:108': 'House Dunn',
  'houses:109': 'House Durrandon',
  'houses:11': 'House Baelish of the Fingers',
  'houses:110': 'House Durwell',
  'houses:111': 'House Dustin of Barrowton',
  'houses:112': 'House Edgerton',
  'houses:113': 'House Egen',
  'houses:114': 'House Elesham of the Paps',
  'houses:115': 'House Erenford',
  'houses:116': 'House Errol of Haystack Hall',
  'houses:117': 'House Estermont of Greenstone',
  'houses:118': 'House Estren of Wyndhall',
  'houses:119': 'House Falwell',
  'houses:12': 'House Ball',
  'houses:120': 'House Farman of Faircastle',
  'houses:121': 'House Farring',
  'houses:122': 'House Farwynd of Sealskin Point',
  'houses:123': 'House Farwynd of the Lonely Light',
  'houses:124': 'House Fell of Felwood',
  'houses:125': 'House Fenn',
  'houses:126': 'House Ferren',
  'houses:127': 'House Fisher',
  'houses:128': 'House Fisher of the Stony Shore',
  'houses:129': 'House Flint  of the mountains',
  'houses:13': 'House Banefort of Banefort',
  'houses:130': 'House Flint of Breakstone Hill',
  'houses:131': 'House Flint of Flint\'s Finger',
  'houses:132': 'House Flint of Widow\'s Watch',
  'houses:133': 'House Florent of Brightwater Keep',
  'houses:134': 'House Follard',
  'houses:135': 'House Foote',
  'houses:136': 'House Foote of Nightsong',
  'houses:137': 'House Footly of Tumbleton',
  'houses:138': 'House Forrester',
  'houses:139': 'House Fossoway of Cider Hall',
  'houses:14': 'House Bar Emmon of Sharp Point',
  'houses:140': 'House Fossoway of New Barrel',
  'houses:141': 'House Fowler of Skyreach',
  'houses:142': 'House Frey of Riverrun',
  'houses:143': 'House Frey of the Crossing',
  'houses:144': 'House Frost',
  'houses:145': 'House Gardener of Highgarden',
  'houses:146': 'House Gargalen of Salt Shore',
  'houses:147': 'House Garner',
  'houses:148': 'House Gaunt',
  'houses:149': 'House Glenmore',
  'houses:15': 'House Baratheon of Dragonstone',
  'houses:150': 'House Glover of Deepwood Motte',
  'houses:151': 'House Goodbrook',
  'houses:152': 'House Goodbrother of Corpse Lake',
  'houses:153': 'House Goodbrother of Crow Spike Keep',
  'houses:154': 'House Goodbrother of Downdelving',
  'houses:155': 'House Goodbrother of Hammerhorn',
  'houses:156': 'House Goodbrother of Orkmont',
  'houses:157': 'House Goodbrother of Shatterstone',
  'houses:158': 'House Gower',
  'houses:159': 'House Graceford of Holyhall',
  'houses:16': 'House Baratheon of King\'s Landing',
  'houses:160': 'House Grafton of Gulltown',
  'houses:161': 'House Grandison of Grandview',
  'houses:162': 'House Graves',
  'houses:163': 'House Greenfield of Greenfield',
  'houses:164': 'House Greengood',
  'houses:165': 'House Greenwood',
  'houses:166': 'House Grell',
  'houses:167': 'House Grey',
  'houses:168': 'House Greyiron of Orkmont',
  'houses:169': 'House Greyjoy of Pyke',
  'houses:17': 'House Baratheon of Storm\'s End',
  'houses:170': 'House Greystark of Wolf\'s Den',
  'houses:171': 'House Grimm of Greyshield',
  'houses:172': 'House Haigh',
  'houses:173': 'House Hamell',
  'houses:174': 'House Harclay',
  'houses:175': 'House Hardy',
  'houses:176': 'House Hardyng',
  'houses:177': 'House Harlaw of Grey Garden',
  'houses:178': 'House Harlaw of Harlaw',
  'houses:179': 'House Harlaw of Harlaw Hall',
  'houses:18': 'House Beesbury of Honeyholt',
  'houses:180': 'House Harlaw of Harridan Hill',
  'houses:181': 'House Harlaw of the Tower of Glimmering',
  'houses:182': 'House Harlton',
  'houses:183': 'House Harroway of Harrenhal',
  'houses:184': 'House Harte',
  'houses:185': 'House Hastwyck',
  'houses:186': 'House Hasty',
  'houses:187': 'House Hawick of Saltpans',
  'houses:188': 'House Hawthorne',
  'houses:189': 'House Hayford of Hayford',
  'houses:19': 'House Belmore of Strongsong',
  'houses:190': 'House Heddle',
  'houses:191': 'House Herston',
  'houses:192': 'House Hersy of Newkeep',
  'houses:193': 'House Hetherspoon',
  'houses:194': 'House Hewett of Oakenshield',
  'houses:195': 'House Hightower of the Hightower',
  'houses:196': 'House Hoare of Orkmont',
  'houses:197': 'House Hogg of Sow\'s Horn',
  'houses:198': 'House Hollard',
  'houses:199': 'House Holt',
  'houses:2': 'House Allyrion of Godsgrace',
  'houses:20': 'House Bettley',
  'houses:200': 'House Holt',
  'houses:201': 'House Hook',
  'houses:202': 'House Hornwood of Hornwood',
  'houses:203': 'House Horpe',
  'houses:204': 'House Hull',
  'houses:205': 'House Humble',
  'houses:206': 'House Hunt',
  'houses:207': 'House Hunter of Longbow Hall',
  'houses:208': 'House Hutcheson',
  'houses:209': 'House Inchfield',
  'houses:21': 'House Bigglestone',
  'houses:210': 'House Ironmaker',
  'houses:211': 'House Ironsmith',
  'houses:212': 'House Jast',
  'houses:213': 'House Jordayne of the Tor',
  'houses:214': 'House Justman',
  'houses:215': 'House Karstark of Karhold',
  'houses:216': 'House Keath',
  'houses:217': 'House Kellington',
  'houses:218': 'House Kenning of Harlaw',
  'houses:219': 'House Kenning of Kayce',
  'houses:22': 'House Blackbar of Bandallon',
  'houses:220': 'House Kettleblack',
  'houses:221': 'House Kidwell of Ivy Hall',
  'houses:222': 'House Knott',
  'houses:223': 'House Kyndall',
  'houses:224': 'House Ladybright',
  'houses:225': 'House Lake',
  'houses:226': 'House Lake',
  'houses:227': 'House Langward',
  'houses:228': 'House Lannett',
  'houses:229': 'House Lannister of Casterly Rock',
  'houses:23': 'House Blackfyre of King\'s Landing',
  'houses:230': 'House Lannister of Darry',
  'houses:231': 'House Lannister of Lannisport',
  'houses:232': 'House Lanny',
  'houses:233': 'House Lantell',
  'houses:234': 'House Lefford of the Golden Tooth',
  'houses:235': 'House Leygood',
  'houses:236': 'House Liddle',
  'houses:237': 'House Lightfoot',
  'houses:238': 'House Lipps',
  'houses:239': 'House Locke of Oldcastle',
  'houses:24': 'House Blackmont of Blackmont',
  'houses:240': 'House Lolliston',
  'houses:241': 'House Long',
  'houses:242': 'House Longthorpe of Longsister',
  'houses:243': 'House Longwaters',
  'houses:244': 'House Lonmouth',
  'houses:245': 'House Lorch',
  'houses:246': 'House Lothston of Harrenhal',
  'houses:247': 'House Lowther',
  'houses:248': 'House Lyberr',
  'houses:249': 'House Lychester',
  'houses:25': 'House Blackmyre',
  'houses:250': 'House Lydden of Deep Den',
  'houses:251': 'House Lynderly of the Snakewood',
  'houses:252': 'House Magnar of Kingshouse',
  'houses:253': 'House Mallery',
  'houses:254': 'House Mallister of Seagard',
  'houses:255': 'House Manderly of White Harbor',
  'houses:256': 'House Manning',
  'houses:257': 'House Manwoody of Kingsgrave',
  'houses:258': 'House Marbrand of Ashemark',
  'houses:259': 'House Marsh',
  'houses:26': 'House Blacktyde of Blacktyde',
  'houses:260': 'House Massey of Stonedance',
  'houses:261': 'House Meadows of Grassy Vale',
  'houses:262': 'House Melcolm of Old Anchor',
  'houses:263': 'House Merlyn of Pebbleton',
  'houses:264': 'House Merryweather of Longtable',
  'houses:265': 'House Mertyns of Mistwood',
  'houses:266': 'House Middlebury',
  'houses:267': 'House Mollen',
  'houses:268': 'House Moore',
  'houses:269': 'House Mooton of Maidenpool',
  'houses:27': 'House Blackwood of Raventree Hall',
  'houses:270': 'House Moreland',
  'houses:271': 'House Mormont of Bear Island',
  'houses:272': 'House Morrigen of Crow\'s Nest',
  'houses:273': 'House Moss',
  'houses:274': 'House Mudd of Oldstones',
  'houses:275': 'House Mullendore of Uplands',
  'houses:276': 'House Musgood',
  'houses:277': 'House Myatt',
  'houses:278': 'House Myre of Harlaw',
  'houses:279': 'House Nayland of Hag\'s Mire',
  'houses:28': 'House Blanetree',
  'houses:280': 'House Netley',
  'houses:281': 'House Norcross',
  'houses:282': 'House Norrey',
  'houses:283': 'House Norridge',
  'houses:284': 'House Nutt',
  'houses:285': 'House Nymeros Martell of Sunspear',
  'houses:286': 'House Oakheart of Old Oak',
  'houses:287': 'House Oldflowers',
  'houses:288': 'House Orkwood of Orkmont',
  'houses:289': 'House Orme',
  'houses:29': 'House Blount',
  'houses:290': 'House Osgrey of Leafy Lake',
  'houses:291': 'House Osgrey of Standfast',
  'houses:292': 'House Overton',
  'houses:293': 'House Paege',
  'houses:294': 'House Parren',
  'houses:295': 'House Payne',
  'houses:296': 'House Peake of Starpike',
  'houses:297': 'House Peasebury of Poddingfield',
  'houses:298': 'House Peat',
  'houses:299': 'House Peckledon',
  'houses:3': 'House Amber',
  'houses:30': 'House Boggs',
  'houses:300': 'House Penrose of Parchments',
  'houses:301': 'House Perryn',
  'houses:302': 'House Piper of Pinkmaiden',
  'houses:303': 'House Plumm',
  'houses:304': 'House Pommingham',
  'houses:305': 'House Poole',
  'houses:306': 'House Prester of Feastfires',
  'houses:307': 'House Pryor of Pebble',
  'houses:308': 'House Pyle',
  'houses:309': 'House Pyne',
  'houses:31': 'House Boggs of Crackclaw Point',
  'houses:310': 'House Qoherys of Harrenhal',
  'houses:311': 'House Qorgyle of Sandstone',
  'houses:312': 'House Quagg',
  'houses:313': 'House Rambton',
  'houses:314': 'House Redbeard',
  'houses:315': 'House Redding',
  'houses:316': 'House Redfort of Redfort',
  'houses:317': 'House Redwyne of the Arbor',
  'houses:318': 'House Reed of Greywater Watch',
  'houses:319': 'House Reyne of Castamere',
  'houses:32': 'House Bole',
  'houses:320': 'House Rhysling',
  'houses:321': 'House Risley',
  'houses:322': 'House Rogers of Amberly',
  'houses:323': 'House Rollingford',
  'houses:324': 'House Roote of Lord Harroway\'s Town',
  'houses:325': 'House Rosby of Rosby',
  'houses:326': 'House Rowan of Goldengrove',
  'houses:327': 'House Roxton of the Ring',
  'houses:328': 'House Royce of Runestone',
  'houses:329': 'House Royce of the Gates of the Moon',
  'houses:33': 'House Bolling',
  'houses:330': 'House Ruthermont',
  'houses:331': 'House Ruttiger',
  'houses:332': 'House Ryder of the Rills',
  'houses:333': 'House Ryger of Willow Wood',
  'houses:334': 'House Rykker of Duskendale',
  'houses:335': 'House Ryswell of the Rills',
  'houses:336': 'House Saltcliffe of Saltcliffe',
  'houses:337': 'House Santagar of Spottswood',
  'houses:338': 'House Sarsfield of Sarsfield',
  'houses:339': 'House Sarwyck',
  'houses:34': 'House Bolton of the Dreadfort',
  'houses:340': 'House Seaworth of Cape Wrath',
  'houses:341': 'House Selmy of Harvest Hall',
  'houses:342': 'House Serrett of Silverhill',
  'houses:343': 'House Serry of Southshield',
  'houses:344': 'House Sharp',
  'houses:345': 'House Shawney',
  'houses:346': 'House Shell',
  'houses:347': 'House Shell',
  'houses:348': 'House Shepherd',
  'houses:349': 'House Shermer of Smithyton',
  'houses:35': 'House Borrell of Sweetsister',
  'houses:350': 'House Shett of Gull Tower',
  'houses:351': 'House Shett of Gulltown',
  'houses:352': 'House Slate of Blackpool',
  'houses:353': 'House Sloane',
  'houses:354': 'House Slynt of Harrenhal',
  'houses:355': 'House Smallwood of Acorn Hall',
  'houses:356': 'House Sparr of Great Wyk',
  'houses:357': 'House Spicer of Castamere',
  'houses:358': 'House Stackhouse',
  'houses:359': 'House Stackspear',
  'houses:36': 'House Botley of Lordsport',
  'houses:360': 'House Staedmon of Broad Arch',
  'houses:361': 'House Stane of Driftwood Hall',
  'houses:362': 'House Stark of Winterfell',
  'houses:363': 'House Staunton of Rook\'s Rest',
  'houses:364': 'House Stokeworth of Stokeworth',
  'houses:365': 'House Stonehouse of Old Wyk',
  'houses:366': 'House Stonetree of Harlaw',
  'houses:367': 'House Stout of Goldgrass',
  'houses:368': 'House Strickland',
  'houses:369': 'House Strong of Harrenhal',
  'houses:37': 'House Bracken of Stone Hedge',
  'houses:370': 'House Sunderland of the Three Sisters',
  'houses:371': 'House Sunderly of Saltcliffe',
  'houses:372': 'House Sunglass of Sweetport Sound',
  'houses:373': 'House Swann of Stonehelm',
  'houses:374': 'House Swyft of Cornfield',
  'houses:375': 'House Swygert',
  'houses:376': 'House Tallhart of Torrhen\'s Square',
  'houses:377': 'House Tarbeck of Tarbeck Hall',
  'houses:378': 'House Targaryen of King\'s Landing',
  'houses:379': 'House Tarly of Horn Hill',
  'houses:38': 'House Branch',
  'houses:380': 'House Tarth of Evenfall Hall',
  'houses:381': 'House Tawney of Orkmont',
  'houses:382': 'House Teague',
  'houses:383': 'House Templeton',
  'houses:384': 'House Terrick',
  'houses:385': 'House Thenn',
  'houses:386': 'House Thorne',
  'houses:387': 'House Toland of Ghost Hill',
  'houses:388': 'House Tollett of the Grey Glen',
  'houses:389': 'House Torrent of Littlesister',
  'houses:39': 'House Branfield',
  'houses:390': 'House Towers',
  'houses:391': 'House Towers of Harrenhal',
  'houses:392': 'House Toyne',
  'houses:393': 'House Trant of Gallowsgrey',
  'houses:394': 'House Tudbury',
  'houses:395': 'House Tully of Riverrun',
  'houses:396': 'House Turnberry',
  'houses:397': 'House Tyrell of Brightwater Keep',
  'houses:398': 'House Tyrell of Highgarden',
  'houses:399': 'House Uffering',
  'houses:4': 'House Ambrose',
  'houses:40': 'House Brax of Hornvale',
  'houses:400': 'House Uller of Hellholt',
  'houses:401': 'House Umber of the Last Hearth',
  'houses:402': 'House Upcliff',
  'houses:403': 'House Vaith of the Red Dunes',
  'houses:404': 'House Vance of Atranta',
  'houses:405': 'House Vance of Wayfarer\'s Rest',
  'houses:406': 'House Varner',
  'houses:407': 'House Velaryon of Driftmark',
  'houses:408': 'House Vikary',
  'houses:409': 'House Volmark',
  'houses:41': 'House Breakstone',
  'houses:410': 'House Vypren',
  'houses:411': 'House Vyrwel of Darkdell',
  'houses:412': 'House Wade',
  'houses:413': 'House Wagstaff',
  'houses:414': 'House Waterman',
  'houses:415': 'House Waxley of Wickenden',
  'houses:416': 'House Wayn',
  'houses:417': 'House Waynwood of Ironoaks',
  'houses:418': 'House Weaver',
  'houses:419': 'House Webber of Coldmoat',
  'houses:42': 'House Briar',
  'houses:420': 'House Wells',
  'houses:421': 'House Wells',
  'houses:422': 'House Wendwater',
  'houses:423': 'House Wensington',
  'houses:424': 'House Westbrook',
  'houses:425': 'House Westerling of the Crag',
  'houses:426': 'House Westford',
  'houses:427': 'House Whent of Harrenhal',
  'houses:428': 'House Whitehill',
  'houses:429': 'House Willum',
  'houses:43': 'House Bridges',
  'houses:430': 'House Wode',
  'houses:431': 'House Woodfoot of Bear Island',
  'houses:432': 'House Woods',
  'houses:433': 'House Woodwright',
  'houses:434': 'House Woolfield',
  'houses:435': 'House Wull',
  'houses:436': 'House Wydman',
  'houses:437': 'House Wyl of the Boneway',
  'houses:438': 'House Wylde of Rain House',
  'houses:439': 'House Wynch of Iron Holt',
  'houses:44': 'House Brightstone',
  'houses:440': 'House Wythers',
  'houses:441': 'House Yarwyck',
  'houses:442': 'House Yelshire',
  'houses:443': 'House Yew',
  'houses:444': 'House Yronwood of Yronwood',
  'houses:45': 'House Brook',
  'houses:46': 'House Broom',
  'houses:47': 'House Brownhill',
  'houses:48': 'House Brune of Brownhollow',
  'houses:49': 'House Brune of the Dyre Den',
  'houses:5': 'House Appleton of Appleton',
  'houses:50': 'House Buckler of Bronzegate',
  'houses:51': 'House Buckwell of the Antlers',
  'houses:52': 'House Bulwer of Blackcrown',
  'houses:53': 'House Burley',
  'houses:54': 'House Bushy',
  'houses:55': 'House Butterwell',
  'houses:56': 'House Byrch',
  'houses:57': 'House Bywater',
  'houses:58': 'House Cafferen of Fawnton',
  'houses:59': 'House Cargyll',
  'houses:6': 'House Arryn of Gulltown',
  'houses:60': 'House Caron of Nightsong',
  'houses:61': 'House Cassel',
  'houses:62': 'House Casterly of Casterly Rock',
  'houses:63': 'House Caswell of Bitterbridge',
  'houses:64': 'House Cave',
  'houses:65': 'House Celtigar of Claw Isle',
  'houses:66': 'House Cerwyn of Cerwyn',
  'houses:67': 'House Chambers',
  'houses:68': 'House Charlton',
  'houses:69': 'House Chelsted',
  'houses:7': 'House Arryn of the Eyrie',
  'houses:70': 'House Chester of Greenshield',
  'houses:71': 'House Chyttering',
  'houses:72': 'House Clegane',
  'houses:73': 'House Clifton',
  'houses:74': 'House Cockshaw',
  'houses:75': 'House Codd',
  'houses:76': 'House Coldwater of Coldwater Burn',
  'houses:77': 'House Cole',
  'houses:78': 'House Condon',
  'houses:79': 'House Conklyn',
  'houses:8': 'House Ashford of Ashford',
  'houses:80': 'House Connington of Griffin\'s Roost',
  'houses:81': 'House Corbray of Heart\'s Home',
  'houses:82': 'House Cordwayner of Hammerhal',
  'houses:83': 'House Costayne of Three Towers',
  'houses:84': 'House Cox of Saltpans',
  'houses:85': 'House Crabb',
  'houses:86': 'House Crakehall of Crakehall',
  'houses:87': 'House Crane of Red Lake',
  'houses:88': 'House Cray',
  'houses:89': 'House Cressey',
  'houses:9': 'House Ashwood',
  'houses:90': 'House Crowl of Deepdown',
  'houses:91': 'House Cuy of Sunhouse',
  'houses:92': 'House Dalt of Lemonwood',
  'houses:93': 'House Dargood',
  'houses:94': 'House Darke',
  'houses:95': 'House Darklyn of Duskendale',
  'houses:96': 'House Darkwood',
  'houses:97': 'House Darry of Darry',
  'houses:98': 'House Dayne of High Hermitage',
  'houses:99': 'House Dayne of Starfall' };

var books = { 'books:1': 'A Game of Thrones',
  'books:10': 'The Rogue Prince',
  'books:11': 'The World of Ice and Fire',
  'books:12': 'A Knight of the Seven Kingdoms',
  'books:2': 'A Clash of Kings',
  'books:3': 'A Storm of Swords',
  'books:4': 'The Hedge Knight',
  'books:5': 'A Feast for Crows',
  'books:6': 'The Sworn Sword',
  'books:7': 'The Mystery Knight',
  'books:8': 'A Dance with Dragons',
  'books:9': 'The Princess and the Queen' };

var request = require('request');
var async = require('async');
if (!process.env.COUCH_URL) {
  throw("environment variable COUCH_URL required");
}
var couchdb = require('cloudant')(process.env.COUCH_URL);
var db = couchdb.db.use('gameofthrones');
var stripdomain = function(str) {
  return str.replace("http://www.anapioficeandfire.com/api/","").replace("/",":");
}



var getPage = function(page, callback) {
  request.get("http://www.anapioficeandfire.com/api/characters?page=" + page, function(err, res, data) {
    if (err) {
      return callback(err, null);
    }
    data = JSON.parse(data);
    if(data.length==0) {
      return callback(true, null);
    }
    for(var i in data) {
      var d = data[i];
      d._id = stripdomain(d.url);
      delete d.url;
      d.father = stripdomain(d.father);
      d.mother = stripdomain(d.mother);
      d.spouse = stripdomain(d.spouse);
      for(var j in d.allegiances) {
        d.allegiances[j] = stripdomain(d.allegiances[j]);
        d.allegiances[j] = houses[d.allegiances[j]]
      }
      for(var j in d.books) {
        d.books[j] = stripdomain(d.books[j]);
        d.books[j] = books[d.books[j]];
      }
      for(var j in d.povBooks) {
        d.povBooks[j] = stripdomain(d.povBooks[j]);
        d.povBooks[j] = books[d.povBooks[j]];
        
      }
    }
    db.bulk({docs: data}, function(err, reply) {
      callback(null, reply);
    });
  
  });
}

var page = 1;
var errorCode= null;

async.doUntil(function(done) {
  console.log("Page", page);
  getPage(page++, function(e, d) {
    errorCode = e;
    done();
  })
}, function() {
  return errorCode != null;
}, function() {
  console.log("Done")
});
